image: node0.10
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  npm:
    email: $$email
    password: $$npmdeploypassword
    username: $$npmdeployusername
    when:
      branch: master
script:
- npm install
- make test
services:
- rgarcia/gearmand
