env:
- npm_drone_username=$$npm_drone_username
- npm_drone_password=$$npm_drone_password
- npm_drone_email=$$npm_drone_email
image: node0.10
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  npm:
    email: $$npm_drone_email
    password: $$npm_drone_password
    registry: https://registry.npmjs.org
    username: $$npm_drone_username
    when:
      branch: master
script:
- npm install npm@2.7.0 -g
- ./publish_nodejitsu.sh
- npm install
- make test
services:
- rgarcia/gearmand

